#ifndef EZTIK_REPONSE_H
#define EZTIK_REPONSE_H

enum
{
    EZTIK_RESPONSE_SESSION_OPEN_FAILED  = 0x1000,
    EZTIK_RESPONSE_SESSION_CLOSE_FAILED = 0x1001,
    EZTIK_RESPONSE_SESSION_ALREADY_OPEN = 0x1002,
    EZTIK_RESPONSE_SESSION_NOT_OPEN     = 0x1003,
    EZTIK_RESPONSE_ROS_API_WRITE_FAILED = 0x1004,
};

#endif
